name: CI/CD and Sponsorship

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Add this to allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Build
      run: npm run build
    - name: Deploy to Vercel
      if: github.ref == 'refs/heads/main' && secrets.VERCEL_TOKEN && secrets.ORG_ID && secrets.PROJECT_ID
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID}}
        vercel-project-id: ${{ secrets.PROJECT_ID}}
    - name: Deploy static index.html
      if: github.ref == 'refs/heads/main' && (!secrets.VERCEL_TOKEN || !secrets.ORG_ID || !secrets.PROJECT_ID)
      run: |
        echo "<html><body><h1>Static Index</h1></body></html>" > index.html
        # Add commands to deploy index.html to your static hosting service

  update_sponsors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update sponsors
      uses: JamesIves/github-sponsors-readme-action@1.0.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: 'README.md'
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: 'Update sponsors'
        add: 'README.md'
